#Chapter 1
It's the year 856. Humans desire and greed throughout
 time is the reason most of the world is corrupted.
 After all, evil drives more evil... The fighting is
 mostly between the royalty and the religion, but I'm
 sure you will learn more about this when the time
 comes. So anyway... Who are you?@
#Chapter 1 Name Part 1
It's a pleasure to meet you, %n. Welcome to Black Magic RPG. @
#Chapter 1 Class Picker
Let's put you in a situation. You're relaxing at home,
 nude, when a crazy guy comes out of the bushes clad in
 thick iron armor wielding a barbaric axe curved like a
 pickaxe. What would you gravitate towards as a way to
 defend yourself?
(1) Warrior (You like to wacky wack)

(2) Mage (You like to casty cast)

(3) Rogue (You like to sneaky sneak)@
