#Chapter 1
It's the year 856. Humans desire and greed throughout
 time is the reason most of the world is corrupted.
 After all, evil drives more evil... The fighting is
 mostly between the royalty and the religion, but I'm
 sure you will learn more about this when the time
 comes. So anyway... Who are you?@
#Chapter 1 Name Part 1
It's a pleasure to meet you, %n. Welcome to Black Magic RPG. @
#Chapter 1 Class Picker
Let's put you in a situation. You're relaxing at home,
 nude, when a crazy guy comes out of the bushes clad in
 thick iron armor wielding a barbaric axe curved like a
 pickaxe. What would you gravitate towards as a way to
 defend yourself?@
#Chapter 1 Class Warrior
(1) Warrior (You like to wacky wack)@
#Chapter 1 Class Mage
(2) Mage (You like to casty cast)@
#Chapter 1 Class Rogue
(3) Rogue (You like to sneaky sneak)@
#Chapter 1 Start
Huh... Never would have guessed that. Well anyway, welcome
 to Black Magic RPG. To start, I've entrusted you with some
 gold. Take this, as currency is important. You'll arrive in
 Blackrock shortly. Please look for my friend, Aubrey. It's
 hard to miss her. Hair is crimson like blood, and her eyes
 are green like an emerald. She'll know where to find me.@
#Chapter 1 Interval
PRESS ENTER TO CONTINUE@
