#Location ID
blkrock-cen@
#Location name
Town of Blackrock - Center@
#Location ID
blkrock-cen-desc@
#Location description
You find yourself In front of you lies a grand gothic cathedral.
 The town appears to be made of black cobblestone mostly kept in
 good shape. As good as it could with the horses and people that
 walk these streets daily, anyway.@
#Location ID
blkrock-nrth@
#Location name
Town of Blackrock - North@
#Location ID
blkrock-nrth-desc@
#Location description
Heading north you find yourself in a grittier part of the town. People
 look more rugged and raged. The beautiful black cobblestone crumbles to
 dirt and dust on this side of town.@
